# InfluxDB + Grafana compose file.
# With data persistency
version: '3'

services:
  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - "8086:8086"
      - "2001:2003"
    environment:
      INFLUXDB_DB: "home"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: pass
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_GRAPHITE_ENABLED: "false"
    volumes:
      - /var/lib/docker/volumes:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_PATHS_PROVISIONING: "/grafana/provisioning"
    user: "0"
    links:
      - influxdb
    volumes:
      - /var/lib/docker/volumes:/var/lib/grafana
      - ./grafana:/grafana

  chronograf:
    image: chronograf:latest
    links:
      - influxdb
    volumes:
      - /var/lib/docker/volumes:/var/lib/grafana
    ports:
      - "8087:8888"
  ai-inference:
    image: nkenye1982/edge-mhealth-rpi:v1.0.0
    container_name: ai-inference
    ports:
      - "8000:8000"
  locust:
    image: nkenye1982/edge-locust-rpi:v1.0.0
    container_name: locust
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    environment:
      TARGET_HOST: http://0.0.0.0:8000
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'
